export const MOVIE_TREDING_DATA = 'MOVIE_TREDING_DATA';
export const MOVIE_LATEST_DATA = 'MOVIE_LATEST_DATA';
export const MOVIE_GENRES_DATA = 'MOVIE_GENRES_DATA';

export const TV_TREDING_DATA = 'TV_TREDING_DATA';
export const TV_LATEST_DATA = 'TV_LATEST_DATA';
